language: c
compiler:
        - gcc
#before_install:
#  - sudo add-apt-repository 'ppa:george-edison55/precise-backports' -y
#  - sudo apt-get update -q
#  - sudo apt-get upgrade -y
#install:
#  - sudo apt-get install cmake cmake-data check -y
addons:
        apt:
                sources:
                        -  george-edison55-precise-backports # cmake 3.2.3 
                packages:
                        - cmake
                        - cmake-data
                        - check


script: mkdir -p tests/build && cd tests/build && cmake .. && make && ./tests-printf 

