language: c
compiler:
        - gcc
        - clang
addons:
  apt:
    sources:
    - sourceline: 'ppa:axel-huebl/cmake3.1'
    packages:
    - cmake
    - check

script: mkdir -p tests/build && cd tests/build && cmake .. && make && ./tests-printf 

