language: c
compiler:
        - gcc
        - clang
addons:
  apt:
    sources:
    - sourceline: 'ppa:andykimpe/cmake3'
    packages:
    - cmake3
    - check

script: mkdir -p tests/build && cd tests/build && cmake .. && make && ./tests-printf 

