language: c
compiler:
        - gcc
        - gcc-4.9
        - gcc-5 
        - gcc-6
        - clang
        - clang-3.6
addons:
        apt:
                sources:
                        - george-edison55-precise-backports # cmake 3.2.3
                        - ubuntu-toolchain-r-test # gcc moderm versions
                        - llvm-toolchain-precise-3.6
                packages:
                        - cmake
                        - cmake-data
                        - check
                        - gcc-4.9
                        - gcc-5
                        - gcc-6
                        - clang-3.6



script: mkdir -p tests/build && cd tests/build && cmake .. && make && ./tests-printf  
after_failure:
        - cat /tmp/sumary_test.txt
        - rm /tmp/sumary_test.txt
after_success:
        - cat /tmp/sumary_test.txt
        - rm /tmp/sumary_test.txt
