language: c
compiler:
        - gcc
before_install:
  - sudo add-apt-repository 'ppa:axel-huebl/cmake3.1' -y
  - sudo apt-get update -q
  - sudo apt-get install cmake check -y


script: mkdir -p tests/build && cd tests/build && cmake .. && make && ./tests-printf 

